name: lunar-e2e-pin-rotation-bf8ad0905
on:
  pull_request:
    types: [opened, labeled]
permissions:
  contents: read
jobs:
  ready:
    if: github.event.action == 'opened'
    runs-on: ubuntu-24.04
    steps:
      - run: /bin/echo 'pin rotation PR opened bf8ad0905'
  ci:
    if: github.event.action == 'labeled' && github.event.label.name == 'e2e-pin-rotation-bf8ad0905'
    runs-on: localdev-e2e-test-37233735029-1-github-5-e2e
    steps:
      - run: /bin/echo 'pin rotation CI bf8ad0905'
