name: lunar-e2e-pin-rotation-0b067b925
on:
  pull_request:
    types: [opened, labeled]
permissions:
  contents: read
jobs:
  ready:
    if: github.event.action == 'opened'
    runs-on: ubuntu-24.04
    steps:
      - run: /bin/echo 'pin rotation PR opened 0b067b925'
  ci:
    if: github.event.action == 'labeled' && github.event.label.name == 'e2e-pin-rotation-0b067b925'
    runs-on: localdev-e2e-test-37233062278-1-github-5-e2e
    steps:
      - run: /bin/echo 'pin rotation CI 0b067b925'
