name: lunar-e2e-pin-rotation-133789435
on:
  pull_request:
    types: [opened, labeled]
permissions:
  contents: read
jobs:
  ready:
    if: github.event.action == 'opened'
    runs-on: ubuntu-24.04
    steps:
      - run: /bin/echo 'pin rotation PR opened 133789435'
  ci:
    if: github.event.action == 'labeled' && github.event.label.name == 'e2e-pin-rotation-133789435'
    runs-on: localdev-e2e-test-37204347963-1-github-5-e2e
    steps:
      - run: /bin/echo 'pin rotation CI 133789435'
